CC = gcc

ex_1 :
	$(CC) ex_1.c -o ex_1 -lm

ex_2 : 
	$(CC) ex_2.c -o ex_2

ex_3 :
	$(CC) ex_3.c -o ex_3 -lm

ex_4_5 :
	$(CC) ex_4_5.c -o ex_4_5

ex_6_8 :
	$(CC) ex_6_8.c -o ex_6_8

ex_9 :
	$(CC) ex_9.c -o ex_9

ex_10 :
	$(CC) ex_10.c -o ex_10

clean : 
	rm -f ex_1 ex_2 ex_3 ex_4_5 ex_6_8 ex_9 ex_10
